declare const styles: {
  readonly counterContainer: string;
  readonly counterButtonContainer: string;
  readonly counterButton: string;
  readonly counterNumberDisplay: string;
  readonly "counterButton-blue": string;
  readonly "counterNumberDisplay-blue": string;
  readonly "counterButton-green": string;
  readonly "counterNumberDisplay-green": string;
  readonly "counterButton-yellow": string;
  readonly "counterNumberDisplay-yellow": string;
  readonly counterTitle: string;
  readonly timerContainer: string;
  readonly startStopButton: string;
  readonly resetButton: string;
  readonly timer: string;
  readonly numPadContainer: string;
  readonly numPad: string;
  readonly numPadButton: string;
  readonly startButton: string;
  readonly setTimerButton: string;
};
export = styles;
