/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/

import { AnyQuestion } from '~/db/lib';

declare module 'zapatos/custom' {
  import type * as db from 'zapatos/db';
  export type PgTask_question_jsonb = AnyQuestion
}
