# NOTE: This is based off of the example template here: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms
name: Feature Request
description: File a feature/enhancement request.
title: "[Feature]: "
labels: ["feature"]
projects: ["sfbrigade/6"]
assignees:
  - juliagoolia
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: what-request
    attributes:
      label: What feature or enhancement are you requesting?
      description: Also tell us more details about the requirements for your feature or enhancement. (feel free to also attach screenshots or other media)
      placeholder: Provide more details!
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
