# Command to build docker image:
#   % docker compose build
#
# To run the production image locally, create a .env.production file with the
# appropriate env vars (a copy of .env.local works). Make sure DATABASE_URL
# points to an accessible and initialized database.
# Command to run docker image:
#   % docker compose up

version: "3"

services:
  server:
    build:
      context: ./../..
      dockerfile: ./docker/production/Dockerfile
    image: unsynced/compass:latest # TODO(amantri): Set this to a shared account
    platform: linux/amd64
    command: bash -l -c "npm run start"
    ports:
      - "3000:3000"
