/**
 * @fileoverview gRPC-Web generated client stub for compass
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.19.1
// source: compass.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as compass_pb from './compass_pb';


export class CompassClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetStudents = new grpcWeb.MethodDescriptor(
    '/compass.Compass/GetStudents',
    grpcWeb.MethodType.UNARY,
    compass_pb.GetStudentsRequest,
    compass_pb.GetStudentsResponse,
    (request: compass_pb.GetStudentsRequest) => {
      return request.serializeBinary();
    },
    compass_pb.GetStudentsResponse.deserializeBinary
  );

  getStudents(
    request: compass_pb.GetStudentsRequest,
    metadata: grpcWeb.Metadata | null): Promise<compass_pb.GetStudentsResponse>;

  getStudents(
    request: compass_pb.GetStudentsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: compass_pb.GetStudentsResponse) => void): grpcWeb.ClientReadableStream<compass_pb.GetStudentsResponse>;

  getStudents(
    request: compass_pb.GetStudentsRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: compass_pb.GetStudentsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/compass.Compass/GetStudents',
        request,
        metadata || {},
        this.methodDescriptorGetStudents,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/compass.Compass/GetStudents',
    request,
    metadata || {},
    this.methodDescriptorGetStudents);
  }

}

