# A Compose stack for running supporting services locally during development.
version: "3"

services:
  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2023-05-18T00-05-36Z
    ports:
      - "9000:9000"
      - "9001:9001"
    command: 'server /data --console-address ":9001"'
    volumes:
      - minio:/data

  create-minio-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc config host add myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/compass-files;
      exit 0;
      "

volumes:
  postgres:
  minio:
